services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - PORT=3003 # <--- ADDED: Explicitly set the application's listening port
    restart: always
    build: . # <--- UNCOMMENTED: Coolify will build from your Dockerfile
    # image: ghcr.io/linkwarden/linkwarden:latest # <--- COMMENTED OUT: No longer pulling pre-built image
    ports:
      - 3003:3003 # <--- CHANGED: External and internal port is 3003
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
